# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Move the directory to the second line
# format = '$all$directory$character'

# Inserts a blank line between shell prompts
add_newline = true

# Replace the '❯' symbol in the prompt with '➜'
# ~/.config/starship.toml

# Increase command timeout to prevent timeouts on slower commands like lua
command_timeout = 2000

[lua]
disabled = true

[character]
success_symbol = '[➜](bold green) '
error_symbol = '[➜](bold red) '

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

